on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: packtracker.io
jobs:
  report:
    name: report webpack stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Install dependencies
      - run: npm ci

      # Build and output webpack stats to webpack-stats.json
      - run: npx craco build

      # Send webpack stats and build information to RelativeCI
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          webpackStatsFile: ./build/report.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
