on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: packtracker.io
jobs:
  report:
    name: report webpack stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # https://github.com/actions/setup-node
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - uses: QuaidBartolomei/compressed-size-action@v2
        with:
          pattern: './build/**/*.{js,css,html,json}'

      # Build and output webpack stats to webpack-stats.json
      - run: npx craco build

      # Send webpack stats and build information to RelativeCI
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          webpackStatsFile: ./build/stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
